[package]
name = "nu_plugin_dns"
version = "1.1.0"
authors = ["Skyler Hawthorne <skyler@dead10ck.dev>"]
description = "A DNS utility for nushell"

repository = "https://github.com/dead10ck/nu_plugin_dns"
edition = "2021"
license = "MPL-2.0"
readme = "README.md"
keywords = ["dns", "dig", "nu", "nushell", "plugin"]
categories = ["command-line-utilities"]

[[bin]]
name = "nu_plugin_dns"
bench = false

[lib]
bench = false

[dependencies]
chrono = { version = "0.4", features = [ "std" ], default-features = false }
futures-util = "0.3.28"
nu-plugin = "0.84.0"
nu-protocol = "0.84.0"
# must keep in lockstep with trust-dns
rustls = "0.21.6"
tokio = "1.32.0"
webpki-roots = "0.25.2"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = [ "env-filter" ] }

[dependencies.trust-dns-resolver]
version = "0.23.0"
features = [
  "dnssec-ring",
  "dns-over-rustls",
  "dns-over-https",
  "dns-over-https-rustls",
  "dns-over-quic",
]

[dependencies.trust-dns-proto]
version = "0.23.0"
features = [
  "dnssec-ring",
  "backtrace",
  "dns-over-rustls",
  "dns-over-https",
  "dns-over-https-rustls",
  "dns-over-quic",
]

[dependencies.trust-dns-client]
version = "0.23.0"
features = [
  "dnssec-ring",
  "backtrace",
  "dns-over-rustls",
  "dns-over-https",
  "dns-over-https-rustls",
  "dns-over-quic",
]

# For termux
# [patch.crates-io]
# pwd = { git = "https://gitlab.com/dead10ck/pwd", branch = "termux" }
